<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="15" passed="0" failed="0" skipped="15">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-09T07:49:55 IST" name="Suite" finished-at="2023-04-09T07:50:02 IST" duration-ms="6999">
    <groups>
      <group name="PimPage">
        <method signature="PimPageTest.validateAddEmployee()[pri:1, instance:TestLayer.PimPageTest@b9b00e0]" name="validateAddEmployee" class="TestLayer.PimPageTest"/>
        <method signature="PimPageTest.validateEmployeeList()[pri:2, instance:TestLayer.PimPageTest@b9b00e0]" name="validateEmployeeList" class="TestLayer.PimPageTest"/>
        <method signature="PimPageTest.validateReports()[pri:3, instance:TestLayer.PimPageTest@b9b00e0]" name="validateReports" class="TestLayer.PimPageTest"/>
      </group> <!-- PimPage -->
      <group name="Leave">
        <method signature="LeavePageTest.validateApplyLeave()[pri:2, instance:TestLayer.LeavePageTest@783a467b]" name="validateApplyLeave" class="TestLayer.LeavePageTest"/>
        <method signature="LeavePageTest.validateClickOnLeavePage()[pri:1, instance:TestLayer.LeavePageTest@783a467b]" name="validateClickOnLeavePage" class="TestLayer.LeavePageTest"/>
      </group> <!-- Leave -->
      <group name="Time">
        <method signature="TimePageTest.validateClickOnTime()[pri:1, instance:TestLayer.TimePageTest@12aba8be]" name="validateClickOnTime" class="TestLayer.TimePageTest"/>
      </group> <!-- Time -->
      <group name="Login">
        <method signature="LoginPageTest.logincredentials()[pri:1, instance:TestLayer.LoginPageTest@45099dd3]" name="logincredentials" class="TestLayer.LoginPageTest"/>
      </group> <!-- Login -->
      <group name="Admin">
        <method signature="AdminPageTest.validateAdminPage()[pri:1, instance:TestLayer.AdminPageTest@7db12bb6]" name="validateAdminPage" class="TestLayer.AdminPageTest"/>
        <method signature="AdminPageTest.validateClickOnOrganization()[pri:3, instance:TestLayer.AdminPageTest@7db12bb6]" name="validateClickOnOrganization" class="TestLayer.AdminPageTest"/>
        <method signature="AdminPageTest.validateGeneralInfo()[pri:4, instance:TestLayer.AdminPageTest@7db12bb6]" name="validateGeneralInfo" class="TestLayer.AdminPageTest"/>
        <method signature="AdminPageTest.validateJobPage()[pri:2, instance:TestLayer.AdminPageTest@7db12bb6]" name="validateJobPage" class="TestLayer.AdminPageTest"/>
      </group> <!-- Admin -->
      <group name="Home">
        <method signature="HomePageTest.validateCurrenturl()[pri:2, instance:TestLayer.HomePageTest@273e7444]" name="validateCurrenturl" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateTitle()[pri:1, instance:TestLayer.HomePageTest@273e7444]" name="validateTitle" class="TestLayer.HomePageTest"/>
      </group> <!-- Home -->
      <group name="Recruitment">
        <method signature="RecruitementPageTest.validateCandidates(java.lang.String)[pri:2, instance:TestLayer.RecruitementPageTest@72e5a8e]" name="validateCandidates" class="TestLayer.RecruitementPageTest"/>
        <method signature="RecruitementPageTest.validateRecruitmentpage()[pri:1, instance:TestLayer.RecruitementPageTest@72e5a8e]" name="validateRecruitmentpage" class="TestLayer.RecruitementPageTest"/>
      </group> <!-- Recruitment -->
    </groups>
    <test started-at="2023-04-09T07:49:55 IST" name="Test" finished-at="2023-04-09T07:50:02 IST" duration-ms="6999">
      <class name="TestLayer.RecruitementPageTest">
        <test-method signature="validateRecruitmentpage()[pri:1, instance:TestLayer.RecruitementPageTest@72e5a8e]" started-at="2023-04-09T07:50:02 IST" name="validateRecruitmentpage" depends-on-groups="Leave" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RecruitementPageTest.validateRecruitmentpage()[pri:1, instance:TestLayer.RecruitementPageTest@72e5a8e] depends on not successfully finished methods in group "Leave"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RecruitementPageTest.validateRecruitmentpage()[pri:1, instance:TestLayer.RecruitementPageTest@72e5a8e] depends on not successfully finished methods in group "Leave"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateRecruitmentpage -->
        <test-method signature="validateCandidates(java.lang.String)[pri:2, instance:TestLayer.RecruitementPageTest@72e5a8e]" started-at="2023-04-09T07:50:02 IST" name="validateCandidates" depends-on-groups="Leave" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RecruitementPageTest.validateCandidates(java.lang.String)[pri:2, instance:TestLayer.RecruitementPageTest@72e5a8e] depends on not successfully finished methods in group "Leave"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RecruitementPageTest.validateCandidates(java.lang.String)[pri:2, instance:TestLayer.RecruitementPageTest@72e5a8e] depends on not successfully finished methods in group "Leave"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCandidates -->
      </class> <!-- TestLayer.RecruitementPageTest -->
      <class name="TestLayer.LeavePageTest">
        <test-method signature="validateClickOnLeavePage()[pri:1, instance:TestLayer.LeavePageTest@783a467b]" started-at="2023-04-09T07:50:02 IST" name="validateClickOnLeavePage" depends-on-groups="Admin" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LeavePageTest.validateClickOnLeavePage()[pri:1, instance:TestLayer.LeavePageTest@783a467b] depends on not successfully finished methods in group "Admin"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LeavePageTest.validateClickOnLeavePage()[pri:1, instance:TestLayer.LeavePageTest@783a467b] depends on not successfully finished methods in group "Admin"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateClickOnLeavePage -->
        <test-method signature="validateApplyLeave()[pri:2, instance:TestLayer.LeavePageTest@783a467b]" started-at="2023-04-09T07:50:02 IST" name="validateApplyLeave" depends-on-groups="Admin" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LeavePageTest.validateApplyLeave()[pri:2, instance:TestLayer.LeavePageTest@783a467b] depends on not successfully finished methods in group "Admin"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LeavePageTest.validateApplyLeave()[pri:2, instance:TestLayer.LeavePageTest@783a467b] depends on not successfully finished methods in group "Admin"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateApplyLeave -->
      </class> <!-- TestLayer.LeavePageTest -->
      <class name="TestLayer.HomePageTest">
        <test-method signature="validateTitle()[pri:1, instance:TestLayer.HomePageTest@273e7444]" started-at="2023-04-09T07:50:02 IST" name="validateTitle" depends-on-groups="Login" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateTitle()[pri:1, instance:TestLayer.HomePageTest@273e7444] depends on not successfully finished methods in group "Login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateTitle()[pri:1, instance:TestLayer.HomePageTest@273e7444] depends on not successfully finished methods in group "Login"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateCurrenturl()[pri:2, instance:TestLayer.HomePageTest@273e7444]" started-at="2023-04-09T07:50:02 IST" name="validateCurrenturl" depends-on-groups="Login" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateCurrenturl()[pri:2, instance:TestLayer.HomePageTest@273e7444] depends on not successfully finished methods in group "Login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateCurrenturl()[pri:2, instance:TestLayer.HomePageTest@273e7444] depends on not successfully finished methods in group "Login"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCurrenturl -->
      </class> <!-- TestLayer.HomePageTest -->
      <class name="TestLayer.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestLayer.LoginPageTest@45099dd3]" started-at="2023-04-09T07:49:55 IST" name="setUp" finished-at="2023-04-09T07:50:02 IST" duration-ms="6873" status="FAIL">
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:50898/devtools/browser/780d0c0f-7a72-4522-b03f-e09ef97e7fdd
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-BF9MIV2J', ip: '192.168.43.121', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: ChromeDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:50898/devtools/browser/780d0c0f-7a72-4522-b03f-e09ef97e7fdd
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-BF9MIV2J', ip: '192.168.43.121', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: ChromeDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:106)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:122)
at java.base/java.util.Optional.map(Optional.java:260)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:120)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:48)
at BaseLayer.Baseclass.initialization(Baseclass.java:31)
at TestLayer.LoginPageTest.setUp(LoginPageTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="logincredentials()[pri:1, instance:TestLayer.LoginPageTest@45099dd3]" started-at="2023-04-09T07:50:02 IST" name="logincredentials" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:50898/devtools/browser/780d0c0f-7a72-4522-b03f-e09ef97e7fdd
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-BF9MIV2J', ip: '192.168.43.121', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: ChromeDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:50898/devtools/browser/780d0c0f-7a72-4522-b03f-e09ef97e7fdd
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-BF9MIV2J', ip: '192.168.43.121', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: ChromeDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:106)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:122)
at java.base/java.util.Optional.map(Optional.java:260)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:120)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:48)
at BaseLayer.Baseclass.initialization(Baseclass.java:31)
at TestLayer.LoginPageTest.setUp(LoginPageTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincredentials -->
      </class> <!-- TestLayer.LoginPageTest -->
      <class name="TestLayer.AdminPageTest">
        <test-method signature="validateAdminPage()[pri:1, instance:TestLayer.AdminPageTest@7db12bb6]" started-at="2023-04-09T07:50:02 IST" name="validateAdminPage" depends-on-groups="PimPage" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AdminPageTest.validateAdminPage()[pri:1, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AdminPageTest.validateAdminPage()[pri:1, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAdminPage -->
        <test-method signature="validateJobPage()[pri:2, instance:TestLayer.AdminPageTest@7db12bb6]" started-at="2023-04-09T07:50:02 IST" name="validateJobPage" depends-on-groups="PimPage" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AdminPageTest.validateJobPage()[pri:2, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AdminPageTest.validateJobPage()[pri:2, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateJobPage -->
        <test-method signature="validateClickOnOrganization()[pri:3, instance:TestLayer.AdminPageTest@7db12bb6]" started-at="2023-04-09T07:50:02 IST" name="validateClickOnOrganization" depends-on-groups="PimPage" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AdminPageTest.validateClickOnOrganization()[pri:3, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AdminPageTest.validateClickOnOrganization()[pri:3, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateClickOnOrganization -->
        <test-method signature="validateGeneralInfo()[pri:4, instance:TestLayer.AdminPageTest@7db12bb6]" started-at="2023-04-09T07:50:02 IST" name="validateGeneralInfo" depends-on-groups="PimPage" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AdminPageTest.validateGeneralInfo()[pri:4, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AdminPageTest.validateGeneralInfo()[pri:4, instance:TestLayer.AdminPageTest@7db12bb6] depends on not successfully finished methods in group "PimPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateGeneralInfo -->
      </class> <!-- TestLayer.AdminPageTest -->
      <class name="TestLayer.TimePageTest">
        <test-method signature="validateClickOnTime()[pri:1, instance:TestLayer.TimePageTest@12aba8be]" started-at="2023-04-09T07:50:02 IST" name="validateClickOnTime" depends-on-groups="Leave" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TimePageTest.validateClickOnTime()[pri:1, instance:TestLayer.TimePageTest@12aba8be] depends on not successfully finished methods in group "Leave"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TimePageTest.validateClickOnTime()[pri:1, instance:TestLayer.TimePageTest@12aba8be] depends on not successfully finished methods in group "Leave"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateClickOnTime -->
      </class> <!-- TestLayer.TimePageTest -->
      <class name="TestLayer.PimPageTest">
        <test-method signature="validateAddEmployee()[pri:1, instance:TestLayer.PimPageTest@b9b00e0]" started-at="2023-04-09T07:50:02 IST" name="validateAddEmployee" depends-on-groups="Home" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PimPageTest.validateAddEmployee()[pri:1, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PimPageTest.validateAddEmployee()[pri:1, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAddEmployee -->
        <test-method signature="validateEmployeeList()[pri:2, instance:TestLayer.PimPageTest@b9b00e0]" started-at="2023-04-09T07:50:02 IST" name="validateEmployeeList" depends-on-groups="Home" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PimPageTest.validateEmployeeList()[pri:2, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PimPageTest.validateEmployeeList()[pri:2, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmployeeList -->
        <test-method signature="validateReports()[pri:3, instance:TestLayer.PimPageTest@b9b00e0]" started-at="2023-04-09T07:50:02 IST" name="validateReports" depends-on-groups="Home" finished-at="2023-04-09T07:50:02 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PimPageTest.validateReports()[pri:3, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PimPageTest.validateReports()[pri:3, instance:TestLayer.PimPageTest@b9b00e0] depends on not successfully finished methods in group "Home"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateReports -->
      </class> <!-- TestLayer.PimPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
